[package]
name = "part2"
version = "0.1.0"
authors = ["Evan Davis <cptroot@gmail.com>"]

[dependencies.nom]
version = "^3.1"
features = ["nightly"]

[dependencies.clap]
version = "2.25.0"

[dependencies.nalgebra]
version = "0.13.0"

[dependencies.parse]
path = "../../parse"
